### ISSUE TITLE
Error out of the box

### ISSUE THREAD

**Issue by zagreusinoz** [GetStream/Stream-Example-Vue-Cli#2]
When I try to run this example out of the box I get an error ```VM586:1 GET https://api.stream-io-api.com/api/v1.0/feed/framework_feeds/vue/?api_key=pvjukxquhwfy&location=unspecified 500 ()```

Could you either - update it so it works out of the box or give some basic instructions on how to configure this (specifically on the platform side -- which feeds do we need, etc?)?

**Comment by dwightgunning** [comment]
I'm not able to replicate the issue with a clean clone, `npm install`, and `npm start`.

I recall doing some behind-the-scenes changes to these demo feeds earlier this week in relation to a separate project. This may have resolved the issue you've experienced.

Do you mind trying one more time. If the issue is still present can confirm the payload sent with the 500 error?
